version: "3.7"

services:
    etop:
        container_name: etop-merchant
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 9001:8080
        depends_on:
            - database
            - redis
    database:
        container_name: database
        image: mysql:8.0
        ports:
            -   3306:3306
        environment:
            MYSQL_DATABASE: etop
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        volumes:
            - db-data:/var/lib/mysql
    redis:
        container_name:  redis
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass  "secret"
        ports:
            - 6380:6379

    phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 9002:80
      environment:
        - PMA_ARBITRARY=1

   

volumes:
    db-data: ~